### ISSUE TITLE
Admin Rechte benötigt

### ISSUE THREAD

**Issue by Travalon** [Tevtongermany/YT2FILE#2]
Ein Verschieben von ffmpeg nach dem Download hat keinen Mehrwert.
Von großem Nachteil ist jedoch, das Administratorrechte benötigt werden. Das liegt am Zielort C:\ .
Unabhängig von den Zugriffsrechten ist C:\ kein Ort an dem Programme abgelegt werden sollten und dürfen.

Mein Lösungsvorschlag ist, den move nicht auszuführen und ffmpeg dort anzusprechen wo es nach dem entdecken liegt. Im Programmordner. Dieser kann yl_dlp über die Option "ffmpeg_location" beim Aufruf mitgegeben werden.

Siehe Codevorschlag:
https://github.com/Travalon/YT2FILEna/commit/0e24c5d662e944b1266cd2994d5801254b9ab697

**Comment by Tevtongermany** [comment]
Hey 
Ich schau dan mal wenn ich wieder zuhause bin weil ich hab das mal probiert es in die Optionen zu packen aber yt_dlp sagt mir das es kein gültiger key ist

**Comment by Tevtongermany** [comment]
Bin so ungefähr 14 15 Uhr wider zurück aber ich geh mal die Pause ist bald vorbei
